### ISSUE TITLE
Python 3.8 instead of python 3.6

### ISSUE THREAD

**Issue by DKbyo** [DrSnowbird/jdk-mvn-py3#3]
Now is using python 3.8 since the new builds are using Ubuntu 20, not sure if you want to update your README or you want to freeze to Ubuntu 18 like in the other projects, 

maybe you should add a tag for each python version...

**Comment by SinanBarut26** [comment]
Same to me. I changed version to `openkbs/jdk-mvn-py3:v1.2.1`. This version has Python 3.6.9. You can use it temporarily

**Comment by DrSnowbird** [comment]
## Update: openkbs/jdk-mvn-py3:v1.2.3 as the latest maintenance build:
The latest maintenance build v1.2.3 is Ubuntu 18.04 due to the needs of keeping Ubuntu 18.04 as its base image to be used by jdk-mvn-py3-vnc which is having some issue with the Ubuntu 20.04. Hence, there will be splitting (detachment) between jdk-mvn-py3 and jdk-mvn-py3-vnc in terms of using Ubuntu 18.04 or Ubuntu 20.04 as the latest base OS image. This will continue until the issue of Ubuntu 20.04 is resolved related VNC installation later time.

Hence, if you want the Ubuntu 18.04 (with Python 3.6), the latest build is  "**openkbs/jdk-mvn-py3:v1.2.3**" to use.

====
Thanks, guys @SinanBarut26  and @DKbyo,
The latest build is using Ubuntu 20.04 and Python default is 3.8.2. As @SinanBarut26 pointed out that, for users who want to use Python 3.6, please use the Docker Hub image tag "**openkbs/jdk-mvn-py3:v1.2.1**" - the last build image with Python 3.6 on Ubuntu 18.04.
And, to use pip command (due to Ubuntu 20.04 changes), there are two ways to do it as below:
- pip3 install <module>
- python3 -m pip install <module>

**Comment by DrSnowbird** [comment]
With the continuing of sticking to Ubuntu 18.04 (due to migration issue for jdk-mvn-py3-x11 having some compatibility issue), the Python 3 now back to Python 3.6. Hence, until we migrate to Ubuntu 20.04, the Python 3 will be in 3.6.
