### ISSUE TITLE
jdk11

### ISSUE THREAD

**Issue by emrehasan** [DrSnowbird/jdk-mvn-py3#4]
The last jdk11-mvn-py3 image is updated 2 years ago. I really like your approach to provide the Dockerfiles but would like to use "your" image since its "your" code. Will you update the jdk11-mvn-py3 image soon?

**Comment by DrSnowbird** [comment]
Hi @emrehasan,
I will set up jdk11-mvn-py docker hub images soon so that you can directly download from docker hub to use.

Update:
* the latest major updates including using Ubuntu 20.04 and latest OpenJDK 11 are in building now in Docker hub. And, the source GIT is at : https://github.com/DrSnowbird/jdk11-mvn-py3/releases/tag/v1.0.0 (separate from jdk-mvn-py3 due to there are needs for that important base image to support VNC, X11 etc children Containers' images building).
* Please check out both
  * Docker Hub: https://hub.docker.com/repository/docker/openkbs/jdk11-mvn-py3
  * Git: DrSnowbird/jdk11-mvn-py3: https://github.com/DrSnowbird/jdk11-mvn-py3/releases/tag/v1.0.0

Best for your dev efforts!

Updated 2020/11/13:
* The new updated GIT: DrSnowbird/jdk11-mvn-py3 and Hub Docker: https://hub.docker.com/repository/docker/openkbs/jdk11-mvn-py3 both are updated and built done.

Hence, closing the issue now. Thanks for input.
